services:
  online-shop:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./online-shop:/app
      - /app/node_modules

  product-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005" 
    ports:
      - 8081:8080
      - 5005:5005

  basket-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
    ports:
      - 8082:8080

  checkout-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
    ports:
      - 8083:8080

  reverse-proxy:
    image: traefik
    command:
      - --api.insecure=true
      # - --log.level=DEBUG
      - --providers.docker=true
      - --log.format=json
    ports:
      - 80:80
      - 8080:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  keycloak:
    command:
      - start-dev


networks:
  traefik:
    driver: bridge
    name: traefik
