services:
  online-shop:
    build:
      context: ./online-shop
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./online-shop/src:/app/src
  product-service:
    image: !reset null
    build:
      context: ./products
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8081:8080
      - 5005:5005
  basket-service:
    image: !reset null
    build:
      context: ./basket
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8082:8080
  checkout-service:
    image: !reset null
    build:
      context: ./checkout
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8083:8080
      # - 5005:5005
