services:
  products:
    build:
      context: products
      dockerfile: src/main/docker/Dockerfile.jvm
    networks:
      - traefik
      - products
    labels:
      - traefik.http.routers.quarkus.rule=PathPrefix("/api/products")
      - traefik.http.services.quarkus.loadbalancer.server.port=8080
      - traefik.docker.network=traefik

  online-shop:
    build:
      context: online-shop
      dockerfile: Dockerfile
    networks:
      - traefik
    labels:
      - traefik.http.routers.online-shop.rule=PathPrefix("/")
      - traefik.http.services.online-shop.loadbalancer.server.port=3000
      - traefik.docker.network=traefik

  products-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: products
      PGDATA: /data/postgres
    volumes:
      - products-db:/data/postgres
    networks:
      - products
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.de
      PGADMIN_DEFAULT_PASSWORD: postgres
      SCRIPT_NAME: /pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.http.routers.pgadmin.rule=PathPrefix("/pgadmin4")
      - traefik.docker.network=traefik
    tty: true

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      URLS: '[{ url: "/api/products/q/openapi", name: "Products" },]'
      BASE_URL: /api/swagger-ui
    networks:
      - traefik
    labels:
      - traefik.http.routers.swagger-ui.rule=PathPrefix("/api/swagger-ui")
      - traefik.http.services.swagger-ui.loadbalancer.server.port=8080
      - traefik.docker.network=traefik


  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management path_prefix "/management/rabbitmq/"
    labels:
      - traefik.http.routers.rabbitmq.rule=PathPrefix("/management/rabbitmq/")
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
      - traefik.docker.network=traefik
    networks:
      - traefik

  cache:
    image: redis
    command: redis-server

networks:
  products:
    driver: bridge
  traefik:
    external: true
    name: traefik

volumes:
  products-db:
  pgadmin:
