services:
  online-shop:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./online-shop:/app
      - /app/node_modules
  product-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8081:8080
      - 5005:5005
  basket-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8082:8080
  checkout-service:
    environment:
      QUARKUS_LAUNCH_DEVMODE: true
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
    ports:
      - 8083:8080
      # - 5005:5005
