on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy on server
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive      
      - name: Deploy application
        run: sh run-prod.sh
          
    
  
